### ISSUE TITLE
Support for Lua 5.2 (was: Error detected while processing function xolox#luainspect#highlight_cmd..xolox#luainspect#make_request..)

### ISSUE THREAD

**Issue by mxmilkiib** [xolox/vim-lua-inspect#2] opened 2013-05-26 22:19 UTC
I've got vim-misc and vim-lua-inspect installed via NeoBundle, but I'm getting an error;

```
Error detected while processing function xolox#luainspect#highlight_cmd..xolox#luainspect#make_request..<SNR>74_parse_text:
line   16:
error loading module 'luainspect4vim' from file '/home/milk/.vim/bundle/vim-lua-inspect/plugin/../misc/luainspect/luainspect4vim.lua':
Press ENTER or type command to continue
Error detected while processing function xolox#luainspect#highlight_cmd..xolox#luainspect#make_request..<SNR>74_parse_text:
line   16:
^I...lua-inspect/plugin/../misc/luainspect/luainspect4vim.lua:155: <name> expected near 'goto'
```

Here's a screenshot with the error whilst on luainspect4vim.lua:155;
http://i.imgur.com/9uw6QD2.png

Any thoughts would be appreciated, thanks!

**Comment by xolox** [comment] 2013-05-27 16:54
My bad, I haven't actually used Lua 5.2 yet (I should be ashamed :-). IIRC it introduces the goto keyword and I was stupid enough to use that literal name as a table key in the source code, so it blows up (the source code was written and tested against Lua 5.1). I'll see if I can fix it today.

**Comment by xolox** [comment] 2013-05-27 17:10
Right now I don't have time to recompile my Vim against Lua 5.2 so I can't actually verify that the change referenced above (in the issue on GitHub) is all that is needed to get it working okay on Lua 5.2. Can you confirm whether the basic features work with the new release and your Lua 5.2 environment? The bundled version of LuaInspect won't support any Lua 5.2 features yet, for that I'll have to upgrade the embedded version (on the to-do list, but it's long ;-).

Regardless, thanks for the feedback! If this resolves the problem you reported, please close the issue on GitHub. Thank you! And happy Vimming :-)

**Comment by mxmilkiib** [comment] 2013-05-28 01:08
Thank you for checking this! It's getting further but returns a different error now;

```
Error detected while processing function xolox#luainspect#highlight_cmd..xolox#luainspect#make_request..<SNR>76_parse_text:
line   16:
...m-lua-inspect/plugin/../misc/luainspect/metalua/base.lua:9: attempt to call global 'getfenv' (a nil value)
```

Apparently `getfenv` was dropped in 5.2. I tried a straight replacement upgrade of the luainspect files but that throws

```
...lua-inspect/plugin/../misc/luainspect/luainspect/ast.lua:68: attempt to index local 'src' (a nil value)
```

And I'm mostly lost in Lua so apologies I can't help further ;o

**Comment by ShadowCreator** [comment] 2013-07-18 04:48
Hey  milkmiruku I'm getting the same error as you, did you ever end up getting it to work? If not I'll add a new issue

**Comment by xolox** [comment] 2013-07-18 19:38
@woywoy: It won't work without efforts on my side -- the version of luainspect bundled with the Vim plug-in won't run on Lua 5.2 and newer versions of luainspect are incompatible with the Vim plug-in (as it is currently written). Despite the minor version bump, Lua 5.2 is backwards incompatible with Lua 5.1 in several places.

Please don't create a new issue, I'm already considering this issue as a request for Lua 5.2 support (see the edited issue title). Depending on the amount of work involved I might be able to fix this tonight (I'll at least give it a shot :-).

**Comment by xolox** [comment] 2013-07-18 21:10
I just included the latest version of LuaInspect in the vim-lua-inspect plug-in. I tested it in Vim 7.3 with Lua 5.1, but I still don't have a Lua 5.2 enabled Vim, so can either of you confirm whether it now works with Lua 5.2?

**Comment by ShadowCreator** [comment] 2013-07-19 09:38
I can confirm that it is working fine now thanks :)

**Comment by xolox** [comment] 2013-07-20 08:37
@woywoy: Thanks for the confirmation! I'm glad to hear it's working now :-)

@milkmiruku: I'm going to close this issue because @woywoy confirmed that vim-lua-inspect now works with Lua 5.2.

If either of you encounter further issues with Lua 5.2 support feel free to reopen this issue or create a new one. Thanks for the feedback both, and happy Vimming!

**Closed as completed by xolox** 2013-07-20 08:37 UTC
